name: Normal Run
#This workflow is triggered on each PUSH to origin/master
on: push

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: npm install, build and test
      - run: |
        npm install
        npm run build --if-present
        npm run test --if-present