name: Normal Run
#This workflow is triggered on each PUSH to origin/master
on: push

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Code
        run: make
      - name: Normal Run
        run: ./index